"""Initial migration

Revision ID: 004b4d5f760d
Revises: fd752e8fce83
Create Date: 2024-12-09 23:03:11.301953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004b4d5f760d'
down_revision = 'fd752e8fce83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_status', sa.String(length=20), nullable=False))
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('brand',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('availability_status')

    # ### end Alembic commands ###
