"""Add availability_status to vehicles

Revision ID: 212f12e2ad99
Revises: 004b4d5f760d
Create Date: 2024-12-09 23:13:55.233204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212f12e2ad99'
down_revision = '004b4d5f760d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_vehicle')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_status', sa.String(length=20), nullable=False))
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('brand',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('availability_status')

    op.create_table('_alembic_tmp_vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=80), nullable=False),
    sa.Column('model', sa.VARCHAR(length=80), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('price_per_day', sa.FLOAT(), nullable=False),
    sa.Column('availability_status', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
